on:
  workflow_dispatch:

name: bump-version
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Bump version
        id: release
        uses: ltv/standard-version-action@main

      - run: |
          echo "Released version: $VERSION"
        env:
          VERSION: ${{ steps.release.output.version }}
